# Generated by Django 5.2.3 on 2025-07-02 01:00

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('alt_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('about', 'About'), ('contact', 'Contact')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title', models.CharField(max_length=50)),
                ('about_us_body', models.CharField(max_length=500)),
                ('contact_num', models.CharField(max_length=20)),
                ('contact_mail', models.CharField(max_length=60)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_design.designimage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('image_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_design.imagelist')),
            ],
            options={
                'ordering': ['tenant', 'image_list', 'order'],
                'abstract': False,
                'unique_together': {('tenant', 'image_list', 'image')},
            },
        ),
    ]
