# Generated by Django 5.2.3 on 2025-08-29 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_design', '0001_initial'),
        ('tenants', '0004_tenant_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedesign',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
