# Generated by Django 5.2.3 on 2025-09-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_shipping_address_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
