# Generated by Django 5.2.3 on 2025-07-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='color_primary',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
